window.HASH_ATLAS_DATA_EN = {
  "generatedAt": "2026-07-26T19:51:54.517Z",
  "gameBuild": "24383809",
  "locale": "en",
  "sourceRoot": "WTTGSD/Content/RawFiles/WebSites",
  "stats": {
    "siteCount": 51,
    "pageCount": 132,
    "direct": 481,
    "clickable": 371,
    "decoy": 340,
    "mixed": 36,
    "uniqueMarkers": 1156
  },
  "sites": [
    {
      "id": "bizarrepropagation",
      "name": "Bizarre Propagation",
      "pageCount": 1,
      "direct": 3,
      "clickable": 1,
      "decoy": 1,
      "mixed": 0
    },
    {
      "id": "blackhatpost",
      "name": "Blackhat Post",
      "pageCount": 2,
      "direct": 6,
      "clickable": 4,
      "decoy": 6,
      "mixed": 0
    },
    {
      "id": "blushingbrides",
      "name": "Blushing Brides",
      "pageCount": 3,
      "direct": 16,
      "clickable": 16,
      "decoy": 10,
      "mixed": 0
    },
    {
      "id": "buildingafuture",
      "name": "Building A Future",
      "pageCount": 2,
      "direct": 8,
      "clickable": 7,
      "decoy": 7,
      "mixed": 0
    },
    {
      "id": "cavitylease",
      "name": "Cavity Lease",
      "pageCount": 2,
      "direct": 10,
      "clickable": 8,
      "decoy": 6,
      "mixed": 0
    },
    {
      "id": "chevron",
      "name": "Chevron",
      "pageCount": 1,
      "direct": 4,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0
    },
    {
      "id": "crisiscalls",
      "name": "Crisis Calls",
      "pageCount": 3,
      "direct": 9,
      "clickable": 9,
      "decoy": 7,
      "mixed": 0
    },
    {
      "id": "crystalguild",
      "name": "Crystal Guild",
      "pageCount": 2,
      "direct": 10,
      "clickable": 6,
      "decoy": 6,
      "mixed": 0
    },
    {
      "id": "doctormurder",
      "name": "Doctor Murder",
      "pageCount": 1,
      "direct": 6,
      "clickable": 7,
      "decoy": 2,
      "mixed": 0
    },
    {
      "id": "dontwasteit",
      "name": "Don't Waste It",
      "pageCount": 4,
      "direct": 12,
      "clickable": 13,
      "decoy": 12,
      "mixed": 8
    },
    {
      "id": "doughy",
      "name": "Doughy",
      "pageCount": 1,
      "direct": 4,
      "clickable": 6,
      "decoy": 6,
      "mixed": 6
    },
    {
      "id": "drugtickets",
      "name": "Drug Tickets",
      "pageCount": 3,
      "direct": 12,
      "clickable": 9,
      "decoy": 8,
      "mixed": 0
    },
    {
      "id": "ems",
      "name": "Eat My Shit",
      "pageCount": 4,
      "direct": 17,
      "clickable": 14,
      "decoy": 13,
      "mixed": 3
    },
    {
      "id": "encrave",
      "name": "Encrave",
      "pageCount": 3,
      "direct": 9,
      "clickable": 6,
      "decoy": 7,
      "mixed": 0
    },
    {
      "id": "finalstanding",
      "name": "finalStanding",
      "pageCount": 1,
      "direct": 6,
      "clickable": 6,
      "decoy": 3,
      "mixed": 0
    },
    {
      "id": "findlove",
      "name": "FindLove",
      "pageCount": 1,
      "direct": 5,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0
    },
    {
      "id": "foreverfriend",
      "name": "Forever Friend",
      "pageCount": 2,
      "direct": 10,
      "clickable": 8,
      "decoy": 5,
      "mixed": 0
    },
    {
      "id": "forsakengifts",
      "name": "Forsaken Gifts",
      "pageCount": 3,
      "direct": 7,
      "clickable": 11,
      "decoy": 9,
      "mixed": 0
    },
    {
      "id": "iamhere",
      "name": "I Am Here",
      "pageCount": 1,
      "direct": 3,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0
    },
    {
      "id": "jakobssink",
      "name": "Jakobs Sink",
      "pageCount": 1,
      "direct": 6,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0
    },
    {
      "id": "keepsake",
      "name": "Keep Sake",
      "pageCount": 3,
      "direct": 6,
      "clickable": 7,
      "decoy": 7,
      "mixed": 0
    },
    {
      "id": "killforme",
      "name": "Kill For Me",
      "pageCount": 3,
      "direct": 12,
      "clickable": 13,
      "decoy": 12,
      "mixed": 0
    },
    {
      "id": "labmonkey",
      "name": "Lab Monkey",
      "pageCount": 4,
      "direct": 16,
      "clickable": 9,
      "decoy": 8,
      "mixed": 0
    },
    {
      "id": "losttapes",
      "name": "LostTapes",
      "pageCount": 3,
      "direct": 16,
      "clickable": 8,
      "decoy": 8,
      "mixed": 0
    },
    {
      "id": "mamabruguglio",
      "name": "MamaBruguglio",
      "pageCount": 1,
      "direct": 3,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0
    },
    {
      "id": "morsnmoremarket",
      "name": "Mors N More Market",
      "pageCount": 4,
      "direct": 23,
      "clickable": 9,
      "decoy": 9,
      "mixed": 0
    },
    {
      "id": "oneless",
      "name": "Oneless",
      "pageCount": 1,
      "direct": 2,
      "clickable": 2,
      "decoy": 2,
      "mixed": 2
    },
    {
      "id": "orderofnine",
      "name": "Order Of Nine",
      "pageCount": 2,
      "direct": 7,
      "clickable": 8,
      "decoy": 8,
      "mixed": 0
    },
    {
      "id": "overnightsuccess",
      "name": "Overnight Success",
      "pageCount": 2,
      "direct": 5,
      "clickable": 4,
      "decoy": 4,
      "mixed": 0
    },
    {
      "id": "prohibitedstockpile",
      "name": "Prohibited Stockpile",
      "pageCount": 2,
      "direct": 6,
      "clickable": 9,
      "decoy": 9,
      "mixed": 6
    },
    {
      "id": "redhanded",
      "name": "Red Handed",
      "pageCount": 6,
      "direct": 18,
      "clickable": 12,
      "decoy": 11,
      "mixed": 0
    },
    {
      "id": "redtriangle",
      "name": "Red Triangle",
      "pageCount": 1,
      "direct": 4,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0
    },
    {
      "id": "ringring",
      "name": "Ring Ring",
      "pageCount": 2,
      "direct": 8,
      "clickable": 4,
      "decoy": 4,
      "mixed": 2
    },
    {
      "id": "shelter",
      "name": "Shelter",
      "pageCount": 3,
      "direct": 14,
      "clickable": 9,
      "decoy": 9,
      "mixed": 0
    },
    {
      "id": "symphoroschosen",
      "name": "Symphoros Chosen",
      "pageCount": 3,
      "direct": 14,
      "clickable": 8,
      "decoy": 7,
      "mixed": 0
    },
    {
      "id": "synapsedecay",
      "name": "Synapse Decay",
      "pageCount": 5,
      "direct": 23,
      "clickable": 10,
      "decoy": 10,
      "mixed": 0
    },
    {
      "id": "tangodown",
      "name": "Tango Down",
      "pageCount": 4,
      "direct": 15,
      "clickable": 9,
      "decoy": 10,
      "mixed": 0
    },
    {
      "id": "thanksforvisting",
      "name": "Thanks For Visiting!",
      "pageCount": 13,
      "direct": 23,
      "clickable": 22,
      "decoy": 22,
      "mixed": 5
    },
    {
      "id": "thebombmaker",
      "name": "The Bomb Maker",
      "pageCount": 1,
      "direct": 4,
      "clickable": 4,
      "decoy": 4,
      "mixed": 0
    },
    {
      "id": "thegrey",
      "name": "The Grey",
      "pageCount": 6,
      "direct": 19,
      "clickable": 22,
      "decoy": 19,
      "mixed": 1
    },
    {
      "id": "thehall",
      "name": "The Hall",
      "pageCount": 1,
      "direct": 3,
      "clickable": 3,
      "decoy": 2,
      "mixed": 0
    },
    {
      "id": "thehole",
      "name": "The Hole",
      "pageCount": 1,
      "direct": 2,
      "clickable": 1,
      "decoy": 1,
      "mixed": 0
    },
    {
      "id": "thelightwithin",
      "name": "The Light Within",
      "pageCount": 2,
      "direct": 8,
      "clickable": 9,
      "decoy": 9,
      "mixed": 0
    },
    {
      "id": "theloogaroo",
      "name": "The Loogaroo",
      "pageCount": 2,
      "direct": 5,
      "clickable": 5,
      "decoy": 5,
      "mixed": 0
    },
    {
      "id": "theprey",
      "name": "The Prey",
      "pageCount": 1,
      "direct": 3,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0
    },
    {
      "id": "timesharing",
      "name": "Time Sharing",
      "pageCount": 3,
      "direct": 13,
      "clickable": 9,
      "decoy": 8,
      "mixed": 3
    },
    {
      "id": "track06",
      "name": "TRACK06",
      "pageCount": 1,
      "direct": 4,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0
    },
    {
      "id": "viamarisroute",
      "name": "ViaMarisRoute",
      "pageCount": 4,
      "direct": 14,
      "clickable": 8,
      "decoy": 8,
      "mixed": 0
    },
    {
      "id": "voluvision",
      "name": "VoluVision",
      "pageCount": 3,
      "direct": 12,
      "clickable": 6,
      "decoy": 6,
      "mixed": 0
    },
    {
      "id": "worldwideworkers",
      "name": "World Wide Workers",
      "pageCount": 3,
      "direct": 13,
      "clickable": 6,
      "decoy": 6,
      "mixed": 0
    },
    {
      "id": "youthere",
      "name": "You There?",
      "pageCount": 1,
      "direct": 3,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0
    }
  ],
  "pages": [
    {
      "id": "bizarrepropagation/index",
      "siteId": "bizarrepropagation",
      "siteName": "Bizarre Propagation",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/bizarrepropagation/index.html",
      "preview": "previews-en/bizarrepropagation/index.html",
      "direct": 3,
      "clickable": 1,
      "decoy": 1,
      "mixed": 0,
      "uniqueMarkers": 5
    },
    {
      "id": "blackhatpost/index",
      "siteId": "blackhatpost",
      "siteName": "Blackhat Post",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/blackhatpost/index.html",
      "preview": "previews-en/blackhatpost/index.html",
      "direct": 3,
      "clickable": 2,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 8
    },
    {
      "id": "blackhatpost/submit",
      "siteId": "blackhatpost",
      "siteName": "Blackhat Post",
      "pageId": "submit",
      "pageName": "Submit",
      "source": "WTTGSD/Content/RawFiles/WebSites/blackhatpost/submit.html",
      "preview": "previews-en/blackhatpost/submit.html",
      "direct": 3,
      "clickable": 2,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 8
    },
    {
      "id": "blushingbrides/index",
      "siteId": "blushingbrides",
      "siteName": "Blushing Brides",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/blushingbrides/index.html",
      "preview": "previews-en/blushingbrides/index.html",
      "direct": 6,
      "clickable": 4,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 13
    },
    {
      "id": "blushingbrides/join",
      "siteId": "blushingbrides",
      "siteName": "Blushing Brides",
      "pageId": "join",
      "pageName": "Join",
      "source": "WTTGSD/Content/RawFiles/WebSites/blushingbrides/join.html",
      "preview": "previews-en/blushingbrides/join.html",
      "direct": 6,
      "clickable": 5,
      "decoy": 4,
      "mixed": 0,
      "uniqueMarkers": 15
    },
    {
      "id": "blushingbrides/samples",
      "siteId": "blushingbrides",
      "siteName": "Blushing Brides",
      "pageId": "samples",
      "pageName": "Samples",
      "source": "WTTGSD/Content/RawFiles/WebSites/blushingbrides/samples.html",
      "preview": "previews-en/blushingbrides/samples.html",
      "direct": 4,
      "clickable": 7,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 14
    },
    {
      "id": "buildingafuture/index",
      "siteId": "buildingafuture",
      "siteName": "Building A Future",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/buildingafuture/index.html",
      "preview": "previews-en/buildingafuture/index.html",
      "direct": 3,
      "clickable": 3,
      "decoy": 4,
      "mixed": 0,
      "uniqueMarkers": 10
    },
    {
      "id": "buildingafuture/invest",
      "siteId": "buildingafuture",
      "siteName": "Building A Future",
      "pageId": "invest",
      "pageName": "Invest",
      "source": "WTTGSD/Content/RawFiles/WebSites/buildingafuture/invest.html",
      "preview": "previews-en/buildingafuture/invest.html",
      "direct": 5,
      "clickable": 4,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 12
    },
    {
      "id": "cavitylease/index",
      "siteId": "cavitylease",
      "siteName": "Cavity Lease",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/cavitylease/index.html",
      "preview": "previews-en/cavitylease/index.html",
      "direct": 5,
      "clickable": 4,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 12
    },
    {
      "id": "cavitylease/submit",
      "siteId": "cavitylease",
      "siteName": "Cavity Lease",
      "pageId": "submit",
      "pageName": "Submit",
      "source": "WTTGSD/Content/RawFiles/WebSites/cavitylease/submit.html",
      "preview": "previews-en/cavitylease/submit.html",
      "direct": 5,
      "clickable": 4,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 12
    },
    {
      "id": "chevron/index",
      "siteId": "chevron",
      "siteName": "Chevron",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/chevron/Index.html",
      "preview": "previews-en/chevron/index.html",
      "direct": 4,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 10
    },
    {
      "id": "crisiscalls/index",
      "siteId": "crisiscalls",
      "siteName": "Crisis Calls",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/crisiscalls/index.html",
      "preview": "previews-en/crisiscalls/index.html",
      "direct": 4,
      "clickable": 4,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 11
    },
    {
      "id": "crisiscalls/account",
      "siteId": "crisiscalls",
      "siteName": "Crisis Calls",
      "pageId": "account",
      "pageName": "Account",
      "source": "WTTGSD/Content/RawFiles/WebSites/crisiscalls/account.html",
      "preview": "previews-en/crisiscalls/account.html",
      "direct": 3,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 7
    },
    {
      "id": "crisiscalls/resetpassword",
      "siteId": "crisiscalls",
      "siteName": "Crisis Calls",
      "pageId": "resetpassword",
      "pageName": "Reset password",
      "source": "WTTGSD/Content/RawFiles/WebSites/crisiscalls/resetpassword.html",
      "preview": "previews-en/crisiscalls/resetpassword.html",
      "direct": 2,
      "clickable": 3,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 7
    },
    {
      "id": "crystalguild/index",
      "siteId": "crystalguild",
      "siteName": "Crystal Guild",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/crystalguild/index.html",
      "preview": "previews-en/crystalguild/index.html",
      "direct": 5,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 11
    },
    {
      "id": "crystalguild/welcome",
      "siteId": "crystalguild",
      "siteName": "Crystal Guild",
      "pageId": "welcome",
      "pageName": "Welcome",
      "source": "WTTGSD/Content/RawFiles/WebSites/crystalguild/welcome.html",
      "preview": "previews-en/crystalguild/welcome.html",
      "direct": 5,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 11
    },
    {
      "id": "doctormurder/index",
      "siteId": "doctormurder",
      "siteName": "Doctor Murder",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/doctormurder/index.html",
      "preview": "previews-en/doctormurder/index.html",
      "direct": 6,
      "clickable": 7,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 15
    },
    {
      "id": "dontwasteit/index",
      "siteId": "dontwasteit",
      "siteName": "Don't Waste It",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/dontwasteit/index.html",
      "preview": "previews-en/dontwasteit/index.html",
      "direct": 3,
      "clickable": 3,
      "decoy": 3,
      "mixed": 3,
      "uniqueMarkers": 6
    },
    {
      "id": "dontwasteit/holdit",
      "siteId": "dontwasteit",
      "siteName": "Don't Waste It",
      "pageId": "holdit",
      "pageName": "Hold It",
      "source": "WTTGSD/Content/RawFiles/WebSites/dontwasteit/holdit.html",
      "preview": "previews-en/dontwasteit/holdit.html",
      "direct": 3,
      "clickable": 3,
      "decoy": 2,
      "mixed": 1,
      "uniqueMarkers": 7
    },
    {
      "id": "dontwasteit/no",
      "siteId": "dontwasteit",
      "siteName": "Don't Waste It",
      "pageId": "no",
      "pageName": "No",
      "source": "WTTGSD/Content/RawFiles/WebSites/dontwasteit/no.html",
      "preview": "previews-en/dontwasteit/no.html",
      "direct": 3,
      "clickable": 4,
      "decoy": 4,
      "mixed": 4,
      "uniqueMarkers": 7
    },
    {
      "id": "dontwasteit/yes",
      "siteId": "dontwasteit",
      "siteName": "Don't Waste It",
      "pageId": "yes",
      "pageName": "Yes",
      "source": "WTTGSD/Content/RawFiles/WebSites/dontwasteit/yes.html",
      "preview": "previews-en/dontwasteit/yes.html",
      "direct": 3,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 9
    },
    {
      "id": "doughy/index",
      "siteId": "doughy",
      "siteName": "Doughy",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/doughy/index.html",
      "preview": "previews-en/doughy/index.html",
      "direct": 4,
      "clickable": 6,
      "decoy": 6,
      "mixed": 6,
      "uniqueMarkers": 10
    },
    {
      "id": "drugtickets/index",
      "siteId": "drugtickets",
      "siteName": "Drug Tickets",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/drugtickets/index.html",
      "preview": "previews-en/drugtickets/index.html",
      "direct": 4,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 10
    },
    {
      "id": "drugtickets/checkout",
      "siteId": "drugtickets",
      "siteName": "Drug Tickets",
      "pageId": "checkout",
      "pageName": "Checkout",
      "source": "WTTGSD/Content/RawFiles/WebSites/drugtickets/checkout.html",
      "preview": "previews-en/drugtickets/checkout.html",
      "direct": 4,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 10
    },
    {
      "id": "drugtickets/error",
      "siteId": "drugtickets",
      "siteName": "Drug Tickets",
      "pageId": "error",
      "pageName": "Error",
      "source": "WTTGSD/Content/RawFiles/WebSites/drugtickets/error.html",
      "preview": "previews-en/drugtickets/error.html",
      "direct": 4,
      "clickable": 3,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 9
    },
    {
      "id": "ems/index",
      "siteId": "ems",
      "siteName": "Eat My Shit",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/ems/index.html",
      "preview": "previews-en/ems/index.html",
      "direct": 4,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 10
    },
    {
      "id": "ems/faq",
      "siteId": "ems",
      "siteName": "Eat My Shit",
      "pageId": "faq",
      "pageName": "FAQ",
      "source": "WTTGSD/Content/RawFiles/WebSites/ems/faq.html",
      "preview": "previews-en/ems/faq.html",
      "direct": 5,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 11
    },
    {
      "id": "ems/questions",
      "siteId": "ems",
      "siteName": "Eat My Shit",
      "pageId": "questions",
      "pageName": "Questions",
      "source": "WTTGSD/Content/RawFiles/WebSites/ems/questions.html",
      "preview": "previews-en/ems/questions.html",
      "direct": 5,
      "clickable": 4,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 12
    },
    {
      "id": "ems/secret",
      "siteId": "ems",
      "siteName": "Eat My Shit",
      "pageId": "secret",
      "pageName": "Secret page",
      "source": "WTTGSD/Content/RawFiles/WebSites/ems/secret.html",
      "preview": "previews-en/ems/secret.html",
      "direct": 3,
      "clickable": 4,
      "decoy": 4,
      "mixed": 3,
      "uniqueMarkers": 8
    },
    {
      "id": "encrave/index",
      "siteId": "encrave",
      "siteName": "Encrave",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/encrave/index.html",
      "preview": "previews-en/encrave/index.html",
      "direct": 3,
      "clickable": 2,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 8
    },
    {
      "id": "encrave/evident",
      "siteId": "encrave",
      "siteName": "Encrave",
      "pageId": "evident",
      "pageName": "Evident",
      "source": "WTTGSD/Content/RawFiles/WebSites/encrave/evident.html",
      "preview": "previews-en/encrave/evident.html",
      "direct": 3,
      "clickable": 1,
      "decoy": 1,
      "mixed": 0,
      "uniqueMarkers": 5
    },
    {
      "id": "encrave/gateopen",
      "siteId": "encrave",
      "siteName": "Encrave",
      "pageId": "gateopen",
      "pageName": "Open gate",
      "source": "WTTGSD/Content/RawFiles/WebSites/encrave/gateopen.html",
      "preview": "previews-en/encrave/gateopen.html",
      "direct": 3,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 9
    },
    {
      "id": "finalstanding/index",
      "siteId": "finalstanding",
      "siteName": "finalStanding",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/finalstanding/index.html",
      "preview": "previews-en/finalstanding/index.html",
      "direct": 6,
      "clickable": 6,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 15
    },
    {
      "id": "findlove/index",
      "siteId": "findlove",
      "siteName": "FindLove",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/findlove/index.html",
      "preview": "previews-en/findlove/index.html",
      "direct": 5,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 9
    },
    {
      "id": "foreverfriend/index",
      "siteId": "foreverfriend",
      "siteName": "Forever Friend",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/foreverfriend/index.html",
      "preview": "previews-en/foreverfriend/index.html",
      "direct": 6,
      "clickable": 5,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 14
    },
    {
      "id": "foreverfriend/order",
      "siteId": "foreverfriend",
      "siteName": "Forever Friend",
      "pageId": "order",
      "pageName": "Order",
      "source": "WTTGSD/Content/RawFiles/WebSites/foreverfriend/order.html",
      "preview": "previews-en/foreverfriend/order.html",
      "direct": 4,
      "clickable": 3,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 9
    },
    {
      "id": "forsakengifts/index",
      "siteId": "forsakengifts",
      "siteName": "Forsaken Gifts",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/forsakengifts/index.html",
      "preview": "previews-en/forsakengifts/index.html",
      "direct": 3,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 9
    },
    {
      "id": "forsakengifts/gifts",
      "siteId": "forsakengifts",
      "siteName": "Forsaken Gifts",
      "pageId": "gifts",
      "pageName": "Gifts",
      "source": "WTTGSD/Content/RawFiles/WebSites/forsakengifts/gifts.html",
      "preview": "previews-en/forsakengifts/gifts.html",
      "direct": 2,
      "clickable": 4,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 8
    },
    {
      "id": "forsakengifts/order",
      "siteId": "forsakengifts",
      "siteName": "Forsaken Gifts",
      "pageId": "order",
      "pageName": "Order",
      "source": "WTTGSD/Content/RawFiles/WebSites/forsakengifts/order.html",
      "preview": "previews-en/forsakengifts/order.html",
      "direct": 2,
      "clickable": 4,
      "decoy": 4,
      "mixed": 0,
      "uniqueMarkers": 10
    },
    {
      "id": "iamhere/index",
      "siteId": "iamhere",
      "siteName": "I Am Here",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/iamhere/index.html",
      "preview": "previews-en/iamhere/index.html",
      "direct": 3,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 7
    },
    {
      "id": "jakobssink/index",
      "siteId": "jakobssink",
      "siteName": "Jakobs Sink",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/jakobssink/index.html",
      "preview": "previews-en/jakobssink/index.html",
      "direct": 6,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 12
    },
    {
      "id": "keepsake/index",
      "siteId": "keepsake",
      "siteName": "Keep Sake",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/keepsake/index.html",
      "preview": "previews-en/keepsake/index.html",
      "direct": 2,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 8
    },
    {
      "id": "keepsake/contact",
      "siteId": "keepsake",
      "siteName": "Keep Sake",
      "pageId": "contact",
      "pageName": "Contact",
      "source": "WTTGSD/Content/RawFiles/WebSites/keepsake/contact.html",
      "preview": "previews-en/keepsake/contact.html",
      "direct": 2,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 6
    },
    {
      "id": "keepsake/thesearch",
      "siteId": "keepsake",
      "siteName": "Keep Sake",
      "pageId": "thesearch",
      "pageName": "The Search",
      "source": "WTTGSD/Content/RawFiles/WebSites/keepsake/thesearch.html",
      "preview": "previews-en/keepsake/thesearch.html",
      "direct": 2,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 6
    },
    {
      "id": "killforme/index",
      "siteId": "killforme",
      "siteName": "Kill For Me",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/killforme/index.html",
      "preview": "previews-en/killforme/index.html",
      "direct": 4,
      "clickable": 4,
      "decoy": 4,
      "mixed": 0,
      "uniqueMarkers": 12
    },
    {
      "id": "killforme/instructions",
      "siteId": "killforme",
      "siteName": "Kill For Me",
      "pageId": "instructions",
      "pageName": "Instructions",
      "source": "WTTGSD/Content/RawFiles/WebSites/killforme/instructions.html",
      "preview": "previews-en/killforme/instructions.html",
      "direct": 4,
      "clickable": 5,
      "decoy": 4,
      "mixed": 0,
      "uniqueMarkers": 13
    },
    {
      "id": "killforme/targets",
      "siteId": "killforme",
      "siteName": "Kill For Me",
      "pageId": "targets",
      "pageName": "Targets",
      "source": "WTTGSD/Content/RawFiles/WebSites/killforme/targets.html",
      "preview": "previews-en/killforme/targets.html",
      "direct": 4,
      "clickable": 4,
      "decoy": 4,
      "mixed": 0,
      "uniqueMarkers": 12
    },
    {
      "id": "labmonkey/index",
      "siteId": "labmonkey",
      "siteName": "Lab Monkey",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/labmonkey/index.html",
      "preview": "previews-en/labmonkey/index.html",
      "direct": 5,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 11
    },
    {
      "id": "labmonkey/catalog",
      "siteId": "labmonkey",
      "siteName": "Lab Monkey",
      "pageId": "catalog",
      "pageName": "Catalog",
      "source": "WTTGSD/Content/RawFiles/WebSites/labmonkey/catalog.html",
      "preview": "previews-en/labmonkey/catalog.html",
      "direct": 4,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 8
    },
    {
      "id": "labmonkey/error",
      "siteId": "labmonkey",
      "siteName": "Lab Monkey",
      "pageId": "error",
      "pageName": "Error",
      "source": "WTTGSD/Content/RawFiles/WebSites/labmonkey/error.html",
      "preview": "previews-en/labmonkey/error.html",
      "direct": 3,
      "clickable": 1,
      "decoy": 1,
      "mixed": 0,
      "uniqueMarkers": 5
    },
    {
      "id": "labmonkey/sign-in",
      "siteId": "labmonkey",
      "siteName": "Lab Monkey",
      "pageId": "sign-in",
      "pageName": "Sign in",
      "source": "WTTGSD/Content/RawFiles/WebSites/labmonkey/sign-in.html",
      "preview": "previews-en/labmonkey/sign-in.html",
      "direct": 4,
      "clickable": 3,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 9
    },
    {
      "id": "losttapes/index",
      "siteId": "losttapes",
      "siteName": "LostTapes",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/losttapes/index.html",
      "preview": "previews-en/losttapes/index.html",
      "direct": 6,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 12
    },
    {
      "id": "losttapes/page2",
      "siteId": "losttapes",
      "siteName": "LostTapes",
      "pageId": "page2",
      "pageName": "Page 2",
      "source": "WTTGSD/Content/RawFiles/WebSites/losttapes/page2.html",
      "preview": "previews-en/losttapes/page2.html",
      "direct": 6,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 12
    },
    {
      "id": "losttapes/purchase",
      "siteId": "losttapes",
      "siteName": "LostTapes",
      "pageId": "purchase",
      "pageName": "Purchase",
      "source": "WTTGSD/Content/RawFiles/WebSites/losttapes/purchase.html",
      "preview": "previews-en/losttapes/purchase.html",
      "direct": 4,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 8
    },
    {
      "id": "mamabruguglio/index",
      "siteId": "mamabruguglio",
      "siteName": "MamaBruguglio",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/mamabruguglio/index.html",
      "preview": "previews-en/mamabruguglio/index.html",
      "direct": 3,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 9
    },
    {
      "id": "morsnmoremarket/index",
      "siteId": "morsnmoremarket",
      "siteName": "Mors N More Market",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/morsnmoremarket/index.html",
      "preview": "previews-en/morsnmoremarket/index.html",
      "direct": 6,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 12
    },
    {
      "id": "morsnmoremarket/menu",
      "siteId": "morsnmoremarket",
      "siteName": "Mors N More Market",
      "pageId": "menu",
      "pageName": "Menu",
      "source": "WTTGSD/Content/RawFiles/WebSites/morsnmoremarket/menu.html",
      "preview": "previews-en/morsnmoremarket/menu.html",
      "direct": 6,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 10
    },
    {
      "id": "morsnmoremarket/order",
      "siteId": "morsnmoremarket",
      "siteName": "Mors N More Market",
      "pageId": "order",
      "pageName": "Order",
      "source": "WTTGSD/Content/RawFiles/WebSites/morsnmoremarket/order.html",
      "preview": "previews-en/morsnmoremarket/order.html",
      "direct": 6,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 10
    },
    {
      "id": "morsnmoremarket/ordersent",
      "siteId": "morsnmoremarket",
      "siteName": "Mors N More Market",
      "pageId": "ordersent",
      "pageName": "Order sent",
      "source": "WTTGSD/Content/RawFiles/WebSites/morsnmoremarket/ordersent.html",
      "preview": "previews-en/morsnmoremarket/ordersent.html",
      "direct": 5,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 9
    },
    {
      "id": "oneless/index",
      "siteId": "oneless",
      "siteName": "Oneless",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/oneless/index.html",
      "preview": "previews-en/oneless/index.html",
      "direct": 2,
      "clickable": 2,
      "decoy": 2,
      "mixed": 2,
      "uniqueMarkers": 4
    },
    {
      "id": "orderofnine/index",
      "siteId": "orderofnine",
      "siteName": "Order Of Nine",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/orderofnine/index.html",
      "preview": "previews-en/orderofnine/index.html",
      "direct": 3,
      "clickable": 4,
      "decoy": 4,
      "mixed": 0,
      "uniqueMarkers": 11
    },
    {
      "id": "orderofnine/join",
      "siteId": "orderofnine",
      "siteName": "Order Of Nine",
      "pageId": "join",
      "pageName": "Join",
      "source": "WTTGSD/Content/RawFiles/WebSites/orderofnine/join.html",
      "preview": "previews-en/orderofnine/join.html",
      "direct": 4,
      "clickable": 4,
      "decoy": 4,
      "mixed": 0,
      "uniqueMarkers": 12
    },
    {
      "id": "overnightsuccess/index",
      "siteId": "overnightsuccess",
      "siteName": "Overnight Success",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/overnightsuccess/index.html",
      "preview": "previews-en/overnightsuccess/index.html",
      "direct": 3,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 7
    },
    {
      "id": "overnightsuccess/purchase",
      "siteId": "overnightsuccess",
      "siteName": "Overnight Success",
      "pageId": "purchase",
      "pageName": "Purchase",
      "source": "WTTGSD/Content/RawFiles/WebSites/overnightsuccess/purchase.html",
      "preview": "previews-en/overnightsuccess/purchase.html",
      "direct": 2,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 6
    },
    {
      "id": "prohibitedstockpile/index",
      "siteId": "prohibitedstockpile",
      "siteName": "Prohibited Stockpile",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/prohibitedstockpile/index.html",
      "preview": "previews-en/prohibitedstockpile/index.html",
      "direct": 3,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 9
    },
    {
      "id": "prohibitedstockpile/nocontent",
      "siteId": "prohibitedstockpile",
      "siteName": "Prohibited Stockpile",
      "pageId": "nocontent",
      "pageName": "No content",
      "source": "WTTGSD/Content/RawFiles/WebSites/prohibitedstockpile/nocontent.html",
      "preview": "previews-en/prohibitedstockpile/nocontent.html",
      "direct": 3,
      "clickable": 6,
      "decoy": 6,
      "mixed": 6,
      "uniqueMarkers": 9
    },
    {
      "id": "redhanded/index",
      "siteId": "redhanded",
      "siteName": "Red Handed",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/redhanded/index.html",
      "preview": "previews-en/redhanded/index.html",
      "direct": 3,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 7
    },
    {
      "id": "redhanded/login",
      "siteId": "redhanded",
      "siteName": "Red Handed",
      "pageId": "login",
      "pageName": "Login",
      "source": "WTTGSD/Content/RawFiles/WebSites/redhanded/login.html",
      "preview": "previews-en/redhanded/login.html",
      "direct": 3,
      "clickable": 2,
      "decoy": 1,
      "mixed": 0,
      "uniqueMarkers": 6
    },
    {
      "id": "redhanded/post1",
      "siteId": "redhanded",
      "siteName": "Red Handed",
      "pageId": "post1",
      "pageName": "Post 1",
      "source": "WTTGSD/Content/RawFiles/WebSites/redhanded/post1.html",
      "preview": "previews-en/redhanded/post1.html",
      "direct": 3,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 7
    },
    {
      "id": "redhanded/post2",
      "siteId": "redhanded",
      "siteName": "Red Handed",
      "pageId": "post2",
      "pageName": "Post 2",
      "source": "WTTGSD/Content/RawFiles/WebSites/redhanded/post2.html",
      "preview": "previews-en/redhanded/post2.html",
      "direct": 3,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 7
    },
    {
      "id": "redhanded/post4",
      "siteId": "redhanded",
      "siteName": "Red Handed",
      "pageId": "post4",
      "pageName": "Post 4",
      "source": "WTTGSD/Content/RawFiles/WebSites/redhanded/post4.html",
      "preview": "previews-en/redhanded/post4.html",
      "direct": 3,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 7
    },
    {
      "id": "redhanded/post6",
      "siteId": "redhanded",
      "siteName": "Red Handed",
      "pageId": "post6",
      "pageName": "Post 6",
      "source": "WTTGSD/Content/RawFiles/WebSites/redhanded/post6.html",
      "preview": "previews-en/redhanded/post6.html",
      "direct": 3,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 7
    },
    {
      "id": "redtriangle/index",
      "siteId": "redtriangle",
      "siteName": "Red Triangle",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/redtriangle/index.html",
      "preview": "previews-en/redtriangle/index.html",
      "direct": 4,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 10
    },
    {
      "id": "ringring/index",
      "siteId": "ringring",
      "siteName": "Ring Ring",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/ringring/index.html",
      "preview": "previews-en/ringring/index.html",
      "direct": 4,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 8
    },
    {
      "id": "ringring/answer",
      "siteId": "ringring",
      "siteName": "Ring Ring",
      "pageId": "answer",
      "pageName": "Answer",
      "source": "WTTGSD/Content/RawFiles/WebSites/ringring/answer.html",
      "preview": "previews-en/ringring/answer.html",
      "direct": 4,
      "clickable": 2,
      "decoy": 2,
      "mixed": 2,
      "uniqueMarkers": 6
    },
    {
      "id": "shelter/index",
      "siteId": "shelter",
      "siteName": "Shelter",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/shelter/index.html",
      "preview": "previews-en/shelter/index.html",
      "direct": 4,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 10
    },
    {
      "id": "shelter/donate",
      "siteId": "shelter",
      "siteName": "Shelter",
      "pageId": "donate",
      "pageName": "Donate",
      "source": "WTTGSD/Content/RawFiles/WebSites/shelter/donate.html",
      "preview": "previews-en/shelter/donate.html",
      "direct": 5,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 11
    },
    {
      "id": "shelter/events",
      "siteId": "shelter",
      "siteName": "Shelter",
      "pageId": "events",
      "pageName": "Events",
      "source": "WTTGSD/Content/RawFiles/WebSites/shelter/events.html",
      "preview": "previews-en/shelter/events.html",
      "direct": 5,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 11
    },
    {
      "id": "symphoroschosen/index",
      "siteId": "symphoroschosen",
      "siteName": "Symphoros Chosen",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/symphoroschosen/index.html",
      "preview": "previews-en/symphoroschosen/index.html",
      "direct": 6,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 12
    },
    {
      "id": "symphoroschosen/live",
      "siteId": "symphoroschosen",
      "siteName": "Symphoros Chosen",
      "pageId": "live",
      "pageName": "Live",
      "source": "WTTGSD/Content/RawFiles/WebSites/symphoroschosen/live.html",
      "preview": "previews-en/symphoroschosen/live.html",
      "direct": 4,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 8
    },
    {
      "id": "symphoroschosen/sendlinks",
      "siteId": "symphoroschosen",
      "siteName": "Symphoros Chosen",
      "pageId": "sendlinks",
      "pageName": "Send links",
      "source": "WTTGSD/Content/RawFiles/WebSites/symphoroschosen/sendlinks.html",
      "preview": "previews-en/symphoroschosen/sendlinks.html",
      "direct": 4,
      "clickable": 3,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 9
    },
    {
      "id": "synapsedecay/index",
      "siteId": "synapsedecay",
      "siteName": "Synapse Decay",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/synapsedecay/index.html",
      "preview": "previews-en/synapsedecay/index.html",
      "direct": 4,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 8
    },
    {
      "id": "synapsedecay/getmoney",
      "siteId": "synapsedecay",
      "siteName": "Synapse Decay",
      "pageId": "getmoney",
      "pageName": "Get Money",
      "source": "WTTGSD/Content/RawFiles/WebSites/synapsedecay/getmoney.html",
      "preview": "previews-en/synapsedecay/getmoney.html",
      "direct": 4,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 8
    },
    {
      "id": "synapsedecay/myfriends",
      "siteId": "synapsedecay",
      "siteName": "Synapse Decay",
      "pageId": "myfriends",
      "pageName": "My Friends",
      "source": "WTTGSD/Content/RawFiles/WebSites/synapsedecay/myfriends.html",
      "preview": "previews-en/synapsedecay/myfriends.html",
      "direct": 5,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 9
    },
    {
      "id": "synapsedecay/occasionally",
      "siteId": "synapsedecay",
      "siteName": "Synapse Decay",
      "pageId": "occasionally",
      "pageName": "Occasionally",
      "source": "WTTGSD/Content/RawFiles/WebSites/synapsedecay/occasionally.html",
      "preview": "previews-en/synapsedecay/occasionally.html",
      "direct": 4,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 8
    },
    {
      "id": "synapsedecay/succulentmeal",
      "siteId": "synapsedecay",
      "siteName": "Synapse Decay",
      "pageId": "succulentmeal",
      "pageName": "Succulent Meal",
      "source": "WTTGSD/Content/RawFiles/WebSites/synapsedecay/succulentmeal.html",
      "preview": "previews-en/synapsedecay/succulentmeal.html",
      "direct": 6,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 10
    },
    {
      "id": "tangodown/index",
      "siteId": "tangodown",
      "siteName": "Tango Down",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/tangodown/index.html",
      "preview": "previews-en/tangodown/index.html",
      "direct": 3,
      "clickable": 3,
      "decoy": 4,
      "mixed": 0,
      "uniqueMarkers": 10
    },
    {
      "id": "tangodown/hire",
      "siteId": "tangodown",
      "siteName": "Tango Down",
      "pageId": "hire",
      "pageName": "Hire",
      "source": "WTTGSD/Content/RawFiles/WebSites/tangodown/hire.html",
      "preview": "previews-en/tangodown/hire.html",
      "direct": 4,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 8
    },
    {
      "id": "tangodown/payment",
      "siteId": "tangodown",
      "siteName": "Tango Down",
      "pageId": "payment",
      "pageName": "Payment",
      "source": "WTTGSD/Content/RawFiles/WebSites/tangodown/payment.html",
      "preview": "previews-en/tangodown/payment.html",
      "direct": 4,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 8
    },
    {
      "id": "tangodown/results",
      "siteId": "tangodown",
      "siteName": "Tango Down",
      "pageId": "results",
      "pageName": "Results",
      "source": "WTTGSD/Content/RawFiles/WebSites/tangodown/results.html",
      "preview": "previews-en/tangodown/results.html",
      "direct": 4,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 8
    },
    {
      "id": "thanksforvisting/index",
      "siteId": "thanksforvisting",
      "siteName": "Thanks For Visiting!",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/thanksforvisting/index.html",
      "preview": "previews-en/thanksforvisting/index.html",
      "direct": 1,
      "clickable": 1,
      "decoy": 1,
      "mixed": 1,
      "uniqueMarkers": 2
    },
    {
      "id": "thanksforvisting/bar",
      "siteId": "thanksforvisting",
      "siteName": "Thanks For Visiting!",
      "pageId": "bar",
      "pageName": "Bar",
      "source": "WTTGSD/Content/RawFiles/WebSites/thanksforvisting/bar.html",
      "preview": "previews-en/thanksforvisting/bar.html",
      "direct": 3,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 9
    },
    {
      "id": "thanksforvisting/connected",
      "siteId": "thanksforvisting",
      "siteName": "Thanks For Visiting!",
      "pageId": "connected",
      "pageName": "Connected",
      "source": "WTTGSD/Content/RawFiles/WebSites/thanksforvisting/connected.html",
      "preview": "previews-en/thanksforvisting/connected.html",
      "direct": 2,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 6
    },
    {
      "id": "thanksforvisting/creepy",
      "siteId": "thanksforvisting",
      "siteName": "Thanks For Visiting!",
      "pageId": "creepy",
      "pageName": "Creepy",
      "source": "WTTGSD/Content/RawFiles/WebSites/thanksforvisting/creepy.html",
      "preview": "previews-en/thanksforvisting/creepy.html",
      "direct": 1,
      "clickable": 1,
      "decoy": 1,
      "mixed": 1,
      "uniqueMarkers": 2
    },
    {
      "id": "thanksforvisting/fakemain",
      "siteId": "thanksforvisting",
      "siteName": "Thanks For Visiting!",
      "pageId": "fakemain",
      "pageName": "Fake main page",
      "source": "WTTGSD/Content/RawFiles/WebSites/thanksforvisting/fakemain.html",
      "preview": "previews-en/thanksforvisting/fakemain.html",
      "direct": 1,
      "clickable": 1,
      "decoy": 1,
      "mixed": 1,
      "uniqueMarkers": 2
    },
    {
      "id": "thanksforvisting/jolly",
      "siteId": "thanksforvisting",
      "siteName": "Thanks For Visiting!",
      "pageId": "jolly",
      "pageName": "Jolly",
      "source": "WTTGSD/Content/RawFiles/WebSites/thanksforvisting/jolly.html",
      "preview": "previews-en/thanksforvisting/jolly.html",
      "direct": 2,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 6
    },
    {
      "id": "thanksforvisting/plug",
      "siteId": "thanksforvisting",
      "siteName": "Thanks For Visiting!",
      "pageId": "plug",
      "pageName": "Plug",
      "source": "WTTGSD/Content/RawFiles/WebSites/thanksforvisting/plug.html",
      "preview": "previews-en/thanksforvisting/plug.html",
      "direct": 2,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 6
    },
    {
      "id": "thanksforvisting/portal",
      "siteId": "thanksforvisting",
      "siteName": "Thanks For Visiting!",
      "pageId": "portal",
      "pageName": "Portal",
      "source": "WTTGSD/Content/RawFiles/WebSites/thanksforvisting/portal.html",
      "preview": "previews-en/thanksforvisting/portal.html",
      "direct": 2,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 6
    },
    {
      "id": "thanksforvisting/sleeptalk",
      "siteId": "thanksforvisting",
      "siteName": "Thanks For Visiting!",
      "pageId": "sleeptalk",
      "pageName": "Sleep Talk",
      "source": "WTTGSD/Content/RawFiles/WebSites/thanksforvisting/sleeptalk.html",
      "preview": "previews-en/thanksforvisting/sleeptalk.html",
      "direct": 1,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 7
    },
    {
      "id": "thanksforvisting/slide2",
      "siteId": "thanksforvisting",
      "siteName": "Thanks For Visiting!",
      "pageId": "slide2",
      "pageName": "Slide 2",
      "source": "WTTGSD/Content/RawFiles/WebSites/thanksforvisting/slide2.html",
      "preview": "previews-en/thanksforvisting/slide2.html",
      "direct": 3,
      "clickable": 2,
      "decoy": 2,
      "mixed": 2,
      "uniqueMarkers": 5
    },
    {
      "id": "thanksforvisting/smile",
      "siteId": "thanksforvisting",
      "siteName": "Thanks For Visiting!",
      "pageId": "smile",
      "pageName": "Smile",
      "source": "WTTGSD/Content/RawFiles/WebSites/thanksforvisting/smile.html",
      "preview": "previews-en/thanksforvisting/smile.html",
      "direct": 2,
      "clickable": 1,
      "decoy": 1,
      "mixed": 0,
      "uniqueMarkers": 4
    },
    {
      "id": "thanksforvisting/ulike",
      "siteId": "thanksforvisting",
      "siteName": "Thanks For Visiting!",
      "pageId": "ulike",
      "pageName": "U Like",
      "source": "WTTGSD/Content/RawFiles/WebSites/thanksforvisting/ulike.html",
      "preview": "previews-en/thanksforvisting/ulike.html",
      "direct": 1,
      "clickable": 1,
      "decoy": 1,
      "mixed": 0,
      "uniqueMarkers": 3
    },
    {
      "id": "thanksforvisting/vision",
      "siteId": "thanksforvisting",
      "siteName": "Thanks For Visiting!",
      "pageId": "vision",
      "pageName": "Vision",
      "source": "WTTGSD/Content/RawFiles/WebSites/thanksforvisting/vision.html",
      "preview": "previews-en/thanksforvisting/vision.html",
      "direct": 2,
      "clickable": 1,
      "decoy": 1,
      "mixed": 0,
      "uniqueMarkers": 4
    },
    {
      "id": "thebombmaker/index",
      "siteId": "thebombmaker",
      "siteName": "The Bomb Maker",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/thebombmaker/index.html",
      "preview": "previews-en/thebombmaker/index.html",
      "direct": 4,
      "clickable": 4,
      "decoy": 4,
      "mixed": 0,
      "uniqueMarkers": 12
    },
    {
      "id": "thegrey/index",
      "siteId": "thegrey",
      "siteName": "The Grey",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/TheGrey/index.html",
      "preview": "previews-en/thegrey/index.html",
      "direct": 3,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 9
    },
    {
      "id": "thegrey/centrum",
      "siteId": "thegrey",
      "siteName": "The Grey",
      "pageId": "centrum",
      "pageName": "Centrum",
      "source": "WTTGSD/Content/RawFiles/WebSites/TheGrey/centrum.html",
      "preview": "previews-en/thegrey/centrum.html",
      "direct": 3,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 9
    },
    {
      "id": "thegrey/deddd",
      "siteId": "thegrey",
      "siteName": "The Grey",
      "pageId": "deddd",
      "pageName": "Deddd",
      "source": "WTTGSD/Content/RawFiles/WebSites/TheGrey/deddd.html",
      "preview": "previews-en/thegrey/deddd.html",
      "direct": 4,
      "clickable": 7,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 14
    },
    {
      "id": "thegrey/inanis",
      "siteId": "thegrey",
      "siteName": "The Grey",
      "pageId": "inanis",
      "pageName": "Inanis",
      "source": "WTTGSD/Content/RawFiles/WebSites/TheGrey/inanis.html",
      "preview": "previews-en/thegrey/inanis.html",
      "direct": 3,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 9
    },
    {
      "id": "thegrey/interius",
      "siteId": "thegrey",
      "siteName": "The Grey",
      "pageId": "interius",
      "pageName": "Interius",
      "source": "WTTGSD/Content/RawFiles/WebSites/TheGrey/interius.html",
      "preview": "previews-en/thegrey/interius.html",
      "direct": 3,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 9
    },
    {
      "id": "thegrey/latus",
      "siteId": "thegrey",
      "siteName": "The Grey",
      "pageId": "latus",
      "pageName": "Latus",
      "source": "WTTGSD/Content/RawFiles/WebSites/TheGrey/latus.html",
      "preview": "previews-en/thegrey/latus.html",
      "direct": 3,
      "clickable": 3,
      "decoy": 4,
      "mixed": 1,
      "uniqueMarkers": 9
    },
    {
      "id": "thehall/index",
      "siteId": "thehall",
      "siteName": "The Hall",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/thehall/index.html",
      "preview": "previews-en/thehall/index.html",
      "direct": 3,
      "clickable": 3,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 8
    },
    {
      "id": "thehole/index",
      "siteId": "thehole",
      "siteName": "The Hole",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/thehole/index.html",
      "preview": "previews-en/thehole/index.html",
      "direct": 2,
      "clickable": 1,
      "decoy": 1,
      "mixed": 0,
      "uniqueMarkers": 4
    },
    {
      "id": "thelightwithin/index",
      "siteId": "thelightwithin",
      "siteName": "The Light Within",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/thelightwithin/index.html",
      "preview": "previews-en/thelightwithin/index.html",
      "direct": 4,
      "clickable": 4,
      "decoy": 4,
      "mixed": 0,
      "uniqueMarkers": 12
    },
    {
      "id": "thelightwithin/saved",
      "siteId": "thelightwithin",
      "siteName": "The Light Within",
      "pageId": "saved",
      "pageName": "Saved",
      "source": "WTTGSD/Content/RawFiles/WebSites/thelightwithin/saved.html",
      "preview": "previews-en/thelightwithin/saved.html",
      "direct": 4,
      "clickable": 5,
      "decoy": 5,
      "mixed": 0,
      "uniqueMarkers": 14
    },
    {
      "id": "theloogaroo/index",
      "siteId": "theloogaroo",
      "siteName": "The Loogaroo",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/theloogaroo/index.html",
      "preview": "previews-en/theloogaroo/index.html",
      "direct": 2,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 8
    },
    {
      "id": "theloogaroo/locations",
      "siteId": "theloogaroo",
      "siteName": "The Loogaroo",
      "pageId": "locations",
      "pageName": "Locations",
      "source": "WTTGSD/Content/RawFiles/WebSites/theloogaroo/locations.html",
      "preview": "previews-en/theloogaroo/locations.html",
      "direct": 3,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 7
    },
    {
      "id": "theprey/index",
      "siteId": "theprey",
      "siteName": "The Prey",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/theprey/index.html",
      "preview": "previews-en/theprey/index.html",
      "direct": 3,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 9
    },
    {
      "id": "timesharing/index",
      "siteId": "timesharing",
      "siteName": "Time Sharing",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/timesharing/index.html",
      "preview": "previews-en/timesharing/index.html",
      "direct": 5,
      "clickable": 3,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 10
    },
    {
      "id": "timesharing/packages",
      "siteId": "timesharing",
      "siteName": "Time Sharing",
      "pageId": "packages",
      "pageName": "Packages",
      "source": "WTTGSD/Content/RawFiles/WebSites/timesharing/packages.html",
      "preview": "previews-en/timesharing/packages.html",
      "direct": 4,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 10
    },
    {
      "id": "timesharing/watch",
      "siteId": "timesharing",
      "siteName": "Time Sharing",
      "pageId": "watch",
      "pageName": "Watch",
      "source": "WTTGSD/Content/RawFiles/WebSites/timesharing/watch.html",
      "preview": "previews-en/timesharing/watch.html",
      "direct": 4,
      "clickable": 3,
      "decoy": 3,
      "mixed": 3,
      "uniqueMarkers": 7
    },
    {
      "id": "track06/index",
      "siteId": "track06",
      "siteName": "TRACK06",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/track06/index.html",
      "preview": "previews-en/track06/index.html",
      "direct": 4,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 8
    },
    {
      "id": "viamarisroute/index",
      "siteId": "viamarisroute",
      "siteName": "ViaMarisRoute",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/viamarisroute/index.html",
      "preview": "previews-en/viamarisroute/index.html",
      "direct": 3,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 7
    },
    {
      "id": "viamarisroute/order",
      "siteId": "viamarisroute",
      "siteName": "ViaMarisRoute",
      "pageId": "order",
      "pageName": "Order",
      "source": "WTTGSD/Content/RawFiles/WebSites/viamarisroute/order.html",
      "preview": "previews-en/viamarisroute/order.html",
      "direct": 3,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 7
    },
    {
      "id": "viamarisroute/secondpage",
      "siteId": "viamarisroute",
      "siteName": "ViaMarisRoute",
      "pageId": "secondpage",
      "pageName": "Page 2",
      "source": "WTTGSD/Content/RawFiles/WebSites/viamarisroute/secondpage.html",
      "preview": "previews-en/viamarisroute/secondpage.html",
      "direct": 4,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 8
    },
    {
      "id": "viamarisroute/thirdpage",
      "siteId": "viamarisroute",
      "siteName": "ViaMarisRoute",
      "pageId": "thirdpage",
      "pageName": "Page 3",
      "source": "WTTGSD/Content/RawFiles/WebSites/viamarisroute/thirdpage.html",
      "preview": "previews-en/viamarisroute/thirdpage.html",
      "direct": 4,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 8
    },
    {
      "id": "voluvision/index",
      "siteId": "voluvision",
      "siteName": "VoluVision",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/voluvision/index.html",
      "preview": "previews-en/voluvision/index.html",
      "direct": 5,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 9
    },
    {
      "id": "voluvision/purchase",
      "siteId": "voluvision",
      "siteName": "VoluVision",
      "pageId": "purchase",
      "pageName": "Purchase",
      "source": "WTTGSD/Content/RawFiles/WebSites/voluvision/purchase.html",
      "preview": "previews-en/voluvision/purchase.html",
      "direct": 3,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 7
    },
    {
      "id": "voluvision/testimonials",
      "siteId": "voluvision",
      "siteName": "VoluVision",
      "pageId": "testimonials",
      "pageName": "Testimonials",
      "source": "WTTGSD/Content/RawFiles/WebSites/voluvision/testimonials.html",
      "preview": "previews-en/voluvision/testimonials.html",
      "direct": 4,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 8
    },
    {
      "id": "worldwideworkers/index",
      "siteId": "worldwideworkers",
      "siteName": "World Wide Workers",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/worldwideworkers/index.html",
      "preview": "previews-en/worldwideworkers/index.html",
      "direct": 4,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 8
    },
    {
      "id": "worldwideworkers/about",
      "siteId": "worldwideworkers",
      "siteName": "World Wide Workers",
      "pageId": "about",
      "pageName": "About",
      "source": "WTTGSD/Content/RawFiles/WebSites/worldwideworkers/about.html",
      "preview": "previews-en/worldwideworkers/about.html",
      "direct": 4,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 8
    },
    {
      "id": "worldwideworkers/submit",
      "siteId": "worldwideworkers",
      "siteName": "World Wide Workers",
      "pageId": "submit",
      "pageName": "Submit",
      "source": "WTTGSD/Content/RawFiles/WebSites/worldwideworkers/submit.html",
      "preview": "previews-en/worldwideworkers/submit.html",
      "direct": 5,
      "clickable": 2,
      "decoy": 2,
      "mixed": 0,
      "uniqueMarkers": 9
    },
    {
      "id": "youthere/index",
      "siteId": "youthere",
      "siteName": "You There?",
      "pageId": "index",
      "pageName": "Home",
      "source": "WTTGSD/Content/RawFiles/WebSites/youthere/index.html",
      "preview": "previews-en/youthere/index.html",
      "direct": 3,
      "clickable": 3,
      "decoy": 3,
      "mixed": 0,
      "uniqueMarkers": 9
    }
  ]
};
